### ISSUE TITLE
Getting individual results for each individual Simringer branch

### ISSUE THREAD

**Issue by elbow** [davehorton/drachtio-fn-b2b-sugar#12]
Hi,

If I call addUri on a Simringer, is there a way to get back the result of that particular branch/call?

IE in our code we have `req._simringer.addUri(remoteUri, additionalCallOpts);`

(we've stashed the simringer on the original req).

In the case I'm looking at, I see:

```
[2020-04-25 15:25:00.166 +0000] DEBUG (83163 on maximus.daviesfam.org): CallManager#_attemptOne: launched call to sip:dlrkmvb1@89ojg2vn5l95.invalid; 2 calls in progress
[2020-04-25 15:25:00.170 +0000] INFO  (83163 on maximus.daviesfam.org): CallManager#attemptOne: call to sip:dlrkmvb1@89ojg2vn5l95.invalid failed with 503
```

Another branch goes on to connect so the whole simringer succeeds.
But this particular branch gets a 503 - can I get my hands on that result?

Thanks,
Steve

**Comment by elbow** [comment]
I did try to .then the addUri - didn't look like addUri returned anything and indeed:

```
[2020-04-25 17:07:04.322 +0000] ERROR (83370 on maximus.daviesfam.org): Error setting up call
    err: {
      "stack":
          TypeError: Cannot read property 'then' of undefined
              at CallProcessor._connectLegs (/Users/steve/rtcproxy/lib/call-processor.js:601:7)
              at /Users/steve/rtcproxy/lib/call-processor.js:548:24
              at Array.forEach (<anonymous>)
              at /Users/steve/rtcproxy/lib/call-processor.js:370:21
      "message": "Cannot read property 'then' of undefined"
    }
```
